org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/hierarchy/cls/InferredOWLClassHierarchyProvider.java
org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/inference/OWLReasonerManagerImpl.java
org.protege.editor.owl/src/main/java/org/protege/editor/owl/ui/tree/OWLObjectTree.java

moved the OWLOntologyChangeListener from
InferredOWLClassHierarchyProvider to OWLReasonerManagerImpl and issuing
fireReclassified() in case of logical axiom changes plus import changes
(which were ignored before). This way all inferences in the UI should be
updated, not only the inferred class hierarchy.  
Not sure the code was/is safe to guarantee that the reasoner processes
changes before fireReclassified() because OWLManager processes listeners
in undefined order. I do not think calling this method within
SwingUtilities.infokeLater() makes it safe.

Addressing #128

---

org.protege.editor.core.application/src/main/java/org/protege/editor/core/update/PluginInstaller.java
pom.xml

Patches from #97 and #98 to allow FaCT++ plugin work on Windows. Should also fix #107, and make plugin downloads more robust in general.

Fix Windows plugin update

---

org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/inference/DisplayedInferencePreferences.java
org.protege.editor.owl/src/main/java/org/protege/editor/owl/model/inference/OWLReasonerManagerImpl.java

I made a small change which catches and ignores the UnsupportedOperationException when executing reasoning task. This way, owl reasoners can throw exception for reasoning tasks that they do not support and Protege will not misbehave (it should act, in principle, the same as if the reasoning task is not enabled).  
The second change is a bit more clever way for a reasoner in non-buffering mode to understand when changes in ontology may require reclassification. Essentially, only logical or import changes to ontologies in the import closure should be considered.

a few small changes for interaction with the reasoner

---

org.protege.editor.core.application/src/main/java/org/protege/editor/core/ui/util/JOptionPaneEx.java

Focusing components inside dialogs is not consistent across various
operating systems and window managers. Overriding the selectInitialValue
method of JOptionPane should disable the behaviour that automatically
puts the focus on the OK button of a dialog window.
I've tested this on Windows 7, MacOS 10.10 and Ubuntu 15.10.
Implements #227.

Focus components consistently inside dialogs

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/transfer/OWLObjectTreeDragGestureListener.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/view/cls/ToldOWLClassHierarchyViewComponent.java

Adds a method to OWObjectTreeDragGestureListener to call underlying tree's method to see
if drag is enabled.
@rsgoncalves the default is false so I added a call to `setDragEnabled` in the existing class, `ToldOWLClassHierarchyViewComponent`, there may be others

Enable ability to disable drag/drop

---

pom.xml
protege-common/pom.xml
protege-desktop/pom.xml
protege-editor-core/pom.xml
protege-editor-owl/pom.xml
protege-launcher/pom.xml

... such as guava, owl-api, log4j, etc.
The dependencies that assumed to be provided in the bundels folder are
moved to protege-launcher, which is included as a dependency with scope
"provided" in other modules.
The "provided" scope is used in maven-bundle-plugin to exclude these
dependencies from the embedded dependencies
(and hence, not export them in Manifest)
Previously this was managed manually, which could be error-prone.
All versions of the dependencies (except those for the java runtime
from the private repository) are now managed in the parent pom.

Centralize dependencies provided by Protege in bundels

---

pom.xml
protege-common/pom.xml
protege-desktop/src/main/assembly/dependency-sets.xml

instead of exporting a (non-existing) package javax.annotation.*
in protege-common

Add jsr305.jar to bundles

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/action/DeleteClassAction.java

Reference to missing package  sun.dc.pr is unnecessary and prevents compile.
Fixes #572.

Remove reference to sun.dc.pr

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/explanation/ExplanationManager.java

When Protege exists, the opened explanation dialogs do not close
which results in explanations not disposed correctly
To address this, we remember the current open explanations in the
ExplanationManager and dispose them when the ExplanationManager
is disposed

Dispose displayed explanations on workbench close. Address #410

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/explanation/ExplanationManager.java

in which case the "componentHiden" event is not dispatched
now use the "windowClosing" event of the window listener in addition
(there was no incorrect behaviour like in #410, but the explanations
were disposed too late, which could result in additional overhead)

Dispose explanation when window is closed using the (x) button

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/OntologyReloader.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/io/OntologyLoader.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/io/OntologySaver.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/ontology/imports/AddImportsStrategy.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/util/ProgressDialog.java

- The problem with stuck progress dialog was likely caused by
the openjdk bug https://bugs.openjdk.java.net/browse/JDK-5109571
using JDialog.dispose() instead of JDialog.setVisible(false)
seems to avoid this bug
- ProgressDialog: dlg.setVisible(false) is no longer necessary since
dlg.displose() takes care about hiding the dialog
- ProgressDialog.setVisible() always uses SwingUtilities.invokeLater()
to ensure that if setVisible(false) is called after setVisible(true)
then the dialog is shown before it is disposed
(this may be not true if one is called on EDT and the other is not)
- ensure that ProgressDialog.setVisible(false) is called after
ProgressDialog.setVisible(true); this was not the case, e.g.,
in OntologySaver if saving finishes before 
ProgressDialog.setVisible(true) is called …

Improve fix for #574

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/OntologyReloader.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/io/OntologyLoader.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/io/OntologySaver.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/ontology/imports/AddImportsStrategy.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/util/ProgressDialog.java

Because loading / saving / reloading blocks the event dispatch thread,
SwingUtilities.invokeLater that were used to show and hide
the progress dialog, were executed *after* these operations finish.
Now revert the changes to execute dlg.setVisible(true) immediately 
after the main task has been submitted. Since it is executed on
event dispatch thread, dialog will be shown immediately.
The dialog will not be hidden before it is shown since 
dlg.setVisible(false) *always* uses SwingUtilities.invokeLater.

Fix delayed progress dialog due to the fix for #574

---

protege-editor-core/schema/explanationpreferencespanel.exsd
protege-editor-core/src/main/java/org/protege/editor/core/ui/explanationpreferences/ExplanationPreferencesPanel.java
protege-editor-core/src/main/java/org/protege/editor/core/ui/explanationpreferences/ExplanationPreferencesPanelPluginJPFImpl.java
protege-editor-core/src/main/java/org/protege/editor/core/ui/explanationpreferences/ExplanationPreferencesPanelPluginLoader.java
protege-editor-core/src/main/resources/plugin.xml
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/explanation/ExplanationPreferencesGeneralPanel.java
protege-editor-owl/src/main/resources/plugin.xml

This patch adds a new explanation preferences menu tab so that explanation plugins can put their preferences under it. This is managed by providing an extension point explanationpreferences.
By default, the explanation preferences menu has just one tab "General" which lists all installed explanation services.

Add explanation preferences menu and extension point

---

protege-editor-core/src/main/java/org/protege/editor/core/ui/tabbedpane/CloseableTabbedPaneUI.java

Protege crashes on closing the last available tab (=> no more open tabs left)

Fixes #678 : Protege crashes when closing all the tabs

---

pom.xml
protege-common/pom.xml
protege-editor-core/pom.xml
protege-editor-core/src/main/java/org/protege/editor/core/ui/list/MListEditButton.java
protege-editor-owl/pom.xml
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/frame/AbstractOWLFrame.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OWLCellRenderer.java

Embedded dependencies are now specified with the "provided" scope.
They are also unpacked in the resulting jar instead of being embedded
(jar in jar).
For example, all classes of mdock are available dirctly from
protege-editor-core, and if someone uses protege-editor-core in maven,
the dependency on madock will not be pulled from maven central.
This should help eliminating duplicate classes on the classpath.
Address #611 since now protege-editor-core is provided as a normal
dependency of protege-editor-owl. Previously it was with the scope
"provided" which means that it was excluded from transitive
dependencies.
As before, the scope "provided" scope is used to distinguish embedded
dependencies from the remaining dependencies when creating bundles

Improve management of embedded dependencies

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OWLCellRenderer.java

in MList the method getMousePosition() was cached, but OWLCellRenderer
calls getMousePosition(boolean) that was not cached
I changed the method in OWLCellRenderer to getMousePosition() and everything now flies ;-)
I am not sure why the boolean flag is needed, but I guess it is possible also to cache the other method call as well.

Fix caching for #723

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/inference/ReasonerUtilities.java

Also, I noticed in the case NO_REASONER_FACTORY_CHOSEN it says "the Reasoner menu" but in the REASONER_NOT_INITIALIZED case it is "the reasoner menu". I guess it should have the same capitalization?

fix typo in warnUserIfReasonerIsNotConfigured

---

protege-editor-owl/src/main/java/org/protege/editor/owl/OWLEditorKit.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/Extensions.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/UIHelper.java

This PR makes Protégé save a new ontology in a file with an extension suitable to the format chosen by the user, instead of systematically using a ".owl" extension regardless of the format.
It attempts to centralise the association between a format and its extensions in a new static `Extensions` class, which can then be used both when saving a new file (to only allow extensions matching the intended save format) and when opening a file (to allow all extensions for all supported formats).
Related to #969, #1012, and #1015.

Save files using format-specific extensions.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/Extensions.java

`.nt` should be the preferred [extension of N-Triples](https://www.w3.org/TR/n-triples/#h2_sec-mediaReg-n-triples). `.n3` is the [extension for Notation3](https://www.w3.org/TeamSubmission/n3/). `.n3` is kept as second choice, as it might in practice be used by mistake for N-Triple files.

`.nt` as preferred extension for N-Triples

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/user/Orcid.java
protege-editor-owl/src/test/java/org/protege/editor/owl/model/user/Orcid_TestCase.java

Closes #1045
CC @matentzn
ORCiD's standard is to use HTTPS, this PR updates the construction of URIs to reflect this.

Use HTTPS for ORCiD

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/obofoundry/OboFoundryRegistryParser.java

The test case `OboFoundryRegistryParser_IT.shouldParseRegistryFromStandardLocation()` fails for me when compiling on Mac OS 12. The reason is that the URL `http://www.obofoundry.org/registry/ontologies.jsonld` returns an HTTP page with status code 301 "Moved Permanently", which points to `https://obofoundry.org/registry/ontologies.jsonld`, but the `InputStream` is not automatically redirected. The `OboFoundryRegistryParser` then tries to parse this HTTP page and fails.
This pull request fixes this by changing the URL for the OBO Foundry registry in `OboFoundryRegistryParser`.

Fixed failing test case for OboFoundryRegistryParser

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/find/OWLEntityFinderImpl.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/clsdescriptioneditor/OWLAutoCompleter.java

This PR restores the possibility to trigger auto-completion by pressing the `TAB` key (discussed in #1072).
It also fixes an (unrelated) problem that was discovered while investigating the auto-completion issue: an `IndexOutOfBoundsException` that can be thrown when the user starts entering a single `'` in the class expression editor. The exception does not actually crash Protégé and does not prevent the user from continuing to use the class expression editor, but it should still be avoided nonetheless.

Restore tab-triggered auto-completion

---

pom.xml

Owlapi version upgraded from `4.5.19` to `4.5.22`:
- No build errors
- All unit tests passing
- 'maven clean package' is successful
Should we check anything else to ensure package is OK? @matentzn

owlapi version upgraded to 4.5.22

---

protege-desktop/src/main/env/linux/run.sh
protege-desktop/src/main/env/platform-independent/run.sh

For the Linux-specific and the platform-independent package (which both relies on a run.sh script to start Protégé), update the run.sh script so that it detects a conf/jvm.conf (either in $HOME/.protege or in the package itself) and applies Java options found in that file.
The configuration file is expected to contain 'key=value' lines. Accepted keys are:
* max_heap_size (java's -Xmx option)
* min_heap_size (java's -Xms option)
* stack_size (java's -Xss option)
* append (allow passing an arbitrary java option)
(For the macOS-specific package, parsing this file is taken care of by the launcher binary.)

Allow to configure Java options

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/util/OboUtilities.java

The `OboUtilities.isOboId` method in `org.protege.editor.owl.model.util` is currently using the `Pattern.find` method to check whether its argument is an OBO ID.
This is inappropriate as the `Pattern.find` method looks for a subsequence within the string, instead of attempting to match the full string. As a result, a bogus OBO ID such as "MONDO:0018299-obsoleted" will be incorrectly identified as a *valid* OBO ID because the `Pattern.find` method will simply stop matching at the first character that does not fit the pattern (the '-'), but will still report that it has find a match.
Here, we need to check that the entire string matches the OBO ID pattern, which is why this commit replaces the use of `Pattern.find` by `Pattern.match`, which does precisely that.
This is also what the …

Do not allow sub-string matching when recognizing OBO IDs.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/OWLEditorKit.java

When saving a file under a user-provided name, we check the name for any extension. If there is no extension or if the extension is not one of the allowed extensions for the chosen file format, we forcibly append an allowed extension to the filename.
This commit updates this behaviour to append an extension only in the case where there is no extension. If the user-provided filename already has an extension, we keep it as it is even if we don't recognize the extension.
closes #1087.

Do not override user-provided extension.

---

protege-editor-core/src/main/java/org/protege/editor/core/ui/util/UIUtil.java

This PR implements a workaround for the file-saving issue reported in #1106.
On macOS, if we don’t get a File from the macOS-specific `MacUIUtil#saveFile()` method, we assume this is due to a failure of that method (or of the underlying JRE) to even show the native file-choosing dialog (as was shown to happen in #1106), and we fallback to the OS-independent method instead of aborting the file-saving operation entirely.
This allow users affected by the “never-showing-native-dialog“ bug to still save their files, at the price of asking users not affected by that same bug to click “cancel” on two consecutive dialogs if they do want to cancel the save operation at the file-choosing step.

Fallback to OS-independent file-saving dialog on macOS

---

protege-editor-core/src/main/java/org/protege/editor/core/ui/menu/MenuBuilder.java

Use the first character of each menu item as a mnemonic. This allows for example to press <kbd>Alt</kbd>+<kbd>F</kbd> to enter the file menu. This does not add a workable mnemonic to the Reasoner menu, because the R is already taken by Refactor. According to <https://bugs.openjdk.org/browse/JDK-4515762> that should actually work since 2012, but even if one of them doesn't work it is still a large step up from having no mnemonic at all. A more generic approach would be to extend the plugin XML files with an extra "mnemonic" attribute and support that, but that would be a much larger change.
This also adds a few mnemonics to inner parent menus but I think that is a positive change anyways.

Add mnemonics (hotkeys) to menu bar. Resolve #1068.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/editor/OWLConstantEditor.java

Set a default datatype rdf:plainLiteral when a language tag is selected. The data type dropdown is disabled as long as a language tag is selected.
I have attached screenshots for the same.

Fixes #767

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/DocumentFormatUpdater.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/OWLModelManagerImpl.java

When updating the document format of the loaded ontology, make sure to also update the format of all ontologies in the imports closure.
closes #1023

Fix Rio Turtle format updating.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OrphanetLinkExtractor.java

It seems the Orphanet website no longer serves resources of the form `/consor/www/cgi-bin/OC_Exp.php`, only `/consor/cgi-bin/OC_Exp.php`, so we update the link extractor accordingly.
closes #1192

Fix the Orphanet link extractor.

---

.github/workflows/publish-to-maven-central.yml

This PR adds a GitHub Action workflow to automatically build packages and publish them on Maven Central upon release.
As suggested by @matthewhorridge in [this comment](https://github.com/protegeproject/protege/pull/1203#issuecomment-2110702022), the only difference here being the addition of the `workflow_dispatch` trigger condition to be able to manually trigger the workflow (I intend to use that to test publishing a build of the current 5.6.3 release, as a way to test the workflow before the 5.6.4 release).

Automatically publish packages on Maven Central.

---

pom.xml
protege-editor-core/pom.xml
protege-editor-owl/pom.xml
protege-launcher/pom.xml

removed mockito-all, are included into mockito-core.
FIX CVE into apache maven assembly plugin
CVE-2023-37460
CVE-2022-4245
CVE-2022-4244
CVE-2020-15250
CVE-2018-1002200
CVE-2017-1000487

removed unnecessary  mockito-all library and FIX CVE

---

pom.xml
protege-desktop/pom.xml
protege-editor-owl/pom.xml

1. Plugin versions are now specified in the parent pom. This also has an advantage that that plugin versions will be checked even if plugins are not used (or used only in profiles).
2. Plugins are updated to the latest versions, except maven-bundle-plugin (with the latest version the bundles get some osgi dependency problems - this needs to be checked)
3. Set the minimal maven version for more reproducible builds and better reporting for `mvn versions:display-plugin-updates`
4. Some obsolete m2e lifecycle-mappings are removed

Improve management of plugin versions

---

pom.xml
protege-editor-core/pom.xml

The new version tries to export the system packages com.apple.eawt, com.apple.eio, sun.swing, which need to be excluded because they are not exported by any other bundle.
I tested protege-mac app and protege-platform-independent (with openjdk 11.0.23 2024-04-16 LTS), which seem to work fine, but I did not test windows and linux apps.

Upgrade maven-bundle-plugin

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/find/OWLEntityFinderImpl.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/OWLObjectHierarchyProviderListener.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OWLCellRenderer.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/RenderingEscapeUtils.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/tree/OWLModelManagerTree.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/tree/OWLObjectTree.java
protege-editor-owl/src/test/java/org/protege/editor/owl/ui/renderer/RenderingEscapeUtils_TestCase.java

Previously this was done only when searching for OWLClasses

Process escape characters when searching for entities, fix #1217

---

.github/workflows/ci.yml
.github/workflows/publish.yml

The maintainers of the 'setup-java' GitHub Action recommends migrating from 'adopt' to 'temurin' [1], given that "AdoptOpenJDK got moved to Eclipse Temurin and won't be updated anymore".
[1] https://github.com/actions/setup-java

Switch GA workflows to use the Temurin JDK.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/hierarchy/ClassHierarchyPreferences.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/action/DisplayDeprecatedEntitiesAction.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/view/AbstractOWLEntityHierarchyViewComponent.java

The setting of the "View > Show deprecated (obsolete) entities" menu option is not persistent and is always reset to its default value (false) whenever Protégé is started or a new ontology is open.
This PR adds a new preference to store that setting so that it is made persistent.

Add persistence for the "show deprecated entities" option.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/OWLPropertyAssertionRowComparator.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/frame/individual/OWLDataPropertyAssertionAxiomFrameSection.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/frame/individual/OWLNegativeDataPropertyAssertionFrameSection.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/frame/individual/OWLNegativeObjectPropertyAssertionFrameSection.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/frame/individual/OWLObjectPropertyAssertionAxiomFrameSection.java
protege-editor-owl/src/test/java/org/protege/editor/owl/ui/OWLPropertyAssertionRowComparator_TestCase.java

refs #605 
Note: This is my first contribution to protege. So I expect some rough edges ;-) .
I tried to address the sorting of data-/object-propertyAssertion in the individual views.
Analogous to the sorting of classAssertionAxioms the assertions are sorted in following order
1. inferred/not inferred
2. the 'displayName' of the property (using the owlObjectComparator)
3. the 'displayName' of the object (using the owlObjectComparator)
I added the sorting to following Sections:
1. dataPropertyAssertionAxioms
2. objectPropertyAssertionAxioms
3. negativeDataPropertyAssertionAxioms
4. negativeObjectPropertyAssertionAxioms
For personal reasons I would love to see this change in the next protege release. Please let me know if further adjustments are required.

sort of data-/objectproperty assertion axioms

---

protege-editor-core/src/main/java/org/protege/editor/core/ui/util/NativeBrowserLauncher.java

This PR updates the `NativeBrowserLauncher` class so that, on GNU/Linux (or similar non-macOS, non-Windows platforms), we try opening a URL using `xdg-open` first, before any other possible browser. This ensures that the URL is opened using the user’s preferred browser (assuming a FreeDesktop.org-compliant environment, which should be the case of most if not all GNU/Linux distributions nowadays).
closes #1263 
Also bundled with that PR are two small changes on that same `NativeBrowserLauncher` class to silence some warnings about (1) the use of a “raw type” `Class` and (2) the use of the deprecated-in-Java-18 `java.lang.Runtime.exec(String)` method.

Use `xdg-open` to spawn browser on GNU/Linux

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/view/AbstractOWLEntityHierarchyViewComponent.java

This PR makes sure that the “show deprecated entities” setting (and its persistence) acts on both the asserted hierarchy view and the inferred hierarchy view, by setting the appropriate filter on both hierarchy providers.

Fix "show deprecated entities" settings in inferred view.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/bioregistry/Bioregistry.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/bioregistry/BioregistryLinkExtractor.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/bioregistry/Resource.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OWLAnnotationCellRenderer2.java

This PR adds a new LinkExtractor that relies on the Bioregistry.io service.
Whenever we need to resolve an ID that looks like a CURIE ("prefix:local") with an as-yet-unseen prefix name, we look up that prefix name on the Bioregistry; if the prefix name is known to the registry, we cache (1) the pattern for the expected format of the local part, and (2) the template for constructing a resolvable URI. Then if the local identifier matches the Bioregistry-provided pattern, we apply the template to return the desired link.
The order in which the extractors are called is slightly modified so that we call:
* first, all the purely local extractors (that do not need to query an online service);
* then the OboFoundry-based extractor (which needs one remote query at initialisation time);
* then the …

Add a Bioregistry.io-based link extractor.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/find/OWLEntityFinderPreferences.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/search/SearchOptions.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/search/SearchOptionsPanel.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/search/SearchPanel.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/search/SearchResultsPanel.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/search/SearchResultsTableModel.java

This PR adds a new search option to show/hide deprecated entities from the search results. This only affects how search results are displayed, not how search is performed (that is, deprecated entities are found during a search regardless of the value of that option) -- this way, users can toggle the option to show or hide deprecated entities without triggering a new search.
closes #1273

Add a 'Show deprecated' option to the search dialog.

---

protege-editor-owl/src/main/java/org/protege/editor/owl/ui/view/annotationproperty/OWLAnnotationPropertyHierarchyViewComponent.java
protege-editor-owl/src/main/java/org/protege/editor/owl/ui/view/individual/OWLIndividualsByTypeViewComponent.java
protege-editor-owl/src/main/resources/plugin.xml

This PR adds a _Deprecate..._ menu item in the context menu for the asserted class hierarchy view, the object, annotation, and data property hierarchy views, and the individuals-by-type view. The item triggers the same action as the _Edit/Deprecate entity..._ main menu item.
Similarly, it adds a _Merge..._ menu item to the same menus, which triggers the same action as the _Edit/Merge entity..._ main menu item.
closes #1228

Allow deprecating and merging entities from context menus

---

protege-editor-owl/src/main/java/org/protege/editor/owl/model/bioregistry/BioregistryLinkExtractor.java
protege-editor-owl/src/main/java/org/protege/editor/owl/model/identifiers/IdentifiersDotOrgLinkExtractor.java

We cannot/should not rely on the link extractors to provide us with a necessarily valid URI. For example, both the Bioregistry and the Identifiers.org extractors will return an invalid URI if the original DOI happens to contain invalid characters (they do not automatically escape characters that are not allowed in a URI).
So we must be ready to catch a URISyntaxException and log a warning if we run into such a link, rather than let an uncaught exception pass through.

Catch exception upon ill-formed extracted links.
